apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-task"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: "{{ .Release.Name }}"
spec:
  template:
    spec:
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: vote-pvc # PVC that provides /app storage
      restartPolicy: OnFailure
      containers:
      - name: task
        image: radial/busyboxplus:git
        #command: ["/bin/sh", "-c", "echo 'Updating template' && sed -i 's/vs/or/g' /app/templates/index.html && echo 'Done updating template'"]
        command: ["/bin/sh"]
        args:
          - -c
          - |
            {
            # Wait for index.html file
            while [ ! -f "/app/templates/index.html" ]; do
              echo "Waiting for index.html file to be ready..."
              sleep 2
            done
            echo "File exists, proceeding..."
            echo 'Updating template'
            sed -i 's/vs/or/g' /app/templates/index.html
            echo 'Done updating template'
            # Wait until curl succeeds
            until curl -Is http://vote:5000 | head -1 | grep -q "HTTP/1.1 200"; do
                echo "Waiting for response... from vote app"
                sleep 5
            done
            echo "Received successful response!"
            } | tee /app/post-hook-output.txt
        volumeMounts:
        - mountPath: /app
          name: app-data
