apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-info"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
  labels:
    app: "{{ .Release.Name }}"
spec:
  template:
    spec:
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: vote-pvc # PVC that provides /app storage
      restartPolicy: OnFailure
      containers:
      - name: info
        image: busybox
        command: ["/bin/sh", "-c", "echo 'Updating template' && sed -i 's/vs/or/g' /app/templates/index.html && echo 'Done updating template'"]
        volumeMounts:
        - mountPath: /app
          name: app-data