apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: my-pvc # PVC that provides /app storage
      initContainers:
        - name: init-copy
          image: dockersamples/examplevotingapp_vote
          command: ["sh", "-c", "cp -r /app/* /mnt/app"]
          volumeMounts:
          - mountPath: /mnt/app
            name: app-data
      containers:
      - image: dockersamples/examplevotingapp_vote
        {{- if .Values.debug.enabled }}
        command: [{{ .Values.debug.startup.command }}]
        {{- end }}
        name: vote
        ports:
        - containerPort: 80
          name: vote
        volumeMounts:
        - mountPath: /app
          name: app-data