apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: {{ .Values.service.nodeport }}
  selector:
    app: vote