apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-task"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded # Uncomment this -> This will tell Helm to cleanup this Job/Pod after it succeeds
    # --
  labels:
    app: "{{ .Release.Name }}"
spec:
  template:
    spec:
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: vote-pvc # PVC that provides /app storage
        - name: config-volume
          configMap:
            name: post-install-script # Mount Config Map file / name of config-map that holds the script
            defaultMode: 0777
      restartPolicy: OnFailure
      containers:
      - name: task
        image: radial/busyboxplus:git
        command: ["/bin/sh"]
        args:
          - -c
          - |
            {
            /config/post-install.sh
            } | tee /app/post-hook-output.txt
        volumeMounts:
        - mountPath: /app
          name: app-data
        - name: config-volume
          mountPath: /config
